### ISSUE TITLE
Page not found  The page you were trying to access doesn't exist or has been removed.  Back

### ISSUE THREAD

**Issue by ashrafalzyoud** [TaoufikMejri/redmine_partial_admin#1]
when i go to users give me error
redmine 4.1

**Comment by TaoufikMejri** [comment]
It works for me. 
I make some modifications in last commit, I think it fixes the issue.

**Comment by ashrafalzyoud** [comment]
when im login to partial admin account and go to administaror menua
give me internal error
Internal error
An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.

Back

**Comment by ashrafalzyoud** [comment]
Completed 500 Internal Server Error in 37ms (ActiveRecord: 10.5ms)
  
ActionView::Template::Error (undefined method `include?' for nil:NilClass):
    1: <div id="admin-menu">
    2:   <%= render_menu :admin_menu %>
    3: </div>
  
plugins/redmine_partial_admin/init.rb:28:in `block in render_menu'
lib/redmine/menu_manager.rb:199:in `block in menu_items_for'
lib/redmine/menu_manager.rb:196:in `each'
lib/redmine/menu_manager.rb:196:in `menu_items_for'
plugins/redmine_partial_admin/init.rb:25:in `render_menu'
app/views/admin/_menu.html.erb:2:in `_06ad9812bc47d1232906f247e89e65a1'
app/views/admin/index.html.erb:5:in `_c6b3fdbd5297d9083d16d44eab8c1f6a'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'

**Comment by ashrafalzyoud** [comment]
@TaoufikMejri

**Comment by ashrafalzyoud** [comment]
perfect brother
